{
 "title": "casper-dashboard",
 "description": "Casper Network Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Network Connectivity Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "peers{job=\"node\"}"
    }
   ]
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(chain_height{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Current Era",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(current_era{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Finalization Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "finalization_time{job=\"node\"}/1000 > 0"
    }
   ]
  },
  { "title": "Network Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Height" }
   ],
   "targets": [
    {
     "expr": "chain_height{job=\"node\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Era Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(current_era{job=\"node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consensus Finalized Block Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Number of Blocks" }
   ],
   "targets": [
    {
     "expr": "amount_of_blocks{job=\"node\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Block Finalization Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "ms", "label": "finalization time" }
   ],
   "targets": [
    {
     "expr": "finalization_time{job=\"node\"} > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Height Interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(chain_height{job=\"node\"})",
     "legendFormat": "Block Height"
    }
   ]
  },
  {
   "title": "Era Change Interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(current_era{job=\"node\"})",
     "legendFormat": "Era Count"
    }
   ]
  },
  {
   "title": "Consensus Finalized Block Interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "dateTimeFromNow", "label": "Number of Blocks" }
   ],
   "targets": [
    {
     "expr": "timestamp(changes(amount_of_blocks{job=\"node\"}[30s]) > 0) * 1000",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Node Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Utilization %",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Disk Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{fstype=\"ext4\", job=\"node-exporter\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Casper Data LMDB Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "file_stat_size_bytes{path=\"/var/lib/casper/casper-node/data.lmdb\", 'xyz'}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pending Deploys",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(pending_deploy{job=\"node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pending Deploys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "pending_deploy{job=\"node\"}",
     "legendFormat": "pending: {{instance}}"
    }
   ]
  },
  {
   "title": "Contract Runtime apply commit p99.9",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(contract_runtime_apply_commit_bucket{job=\"node\"}[30s]))",
     "legendFormat": "commit  {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of Pending Deploys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "rate(pending_deploy{job=\"node\"}[30s])",
     "legendFormat": "pending: {{instance}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "allocated_ram_bytes{job=\"node\"}",
     "legendFormat": "allocated: [{{hostname}}]"
    }
   ]
  },
  {
   "title": "Total Execute Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(contract_runtime_run_execute_count{job=\"node\"})"
    }
   ]
  },
  {
   "title": "Run execute cumulative count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 2, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "contract_runtime_run_execute_count{job=\"node\"}",
     "legendFormat": "count {{instance}}"
    }
   ]
  },
  {
   "title": "Run execute p95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, contract_runtime_run_execute_bucket{job=\"node\"})",
     "legendFormat": "p95  {{instance}}"
    }
   ]
  },
  {
   "title": "Rate of run execute cumulative count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "rate(contract_runtime_run_execute_count{job=\"node\"}[30s])",
     "legendFormat": "count {{instance}}"
    }
   ]
  },
  {
   "title": "Consumed Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "consumed_ram_bytes{job=\"node\"}",
     "legendFormat": "consumed: [{{hostname}}]"
    }
   ]
  },
  {
   "title": "Scheduler Queue Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(scheduler_queue_total_count{job=\"node\"})",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Scheduler Queue Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "scheduler_queue_total_count{job=\"node\"}",
     "legendFormat": "scheduled: {{ hostname }}"
    }
   ]
  },
  {
   "title": "Free Mem Vs Total Mem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 43 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\"}",
     "legendFormat": "free: [{{hostname}}]"
    },
    {
     "expr": "avg(node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "Max mem [{{hostname}}]"
    }
   ]
  },
  {
   "title": "Average Mem (REST vs RPC)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(mem_rest_server{job=\"node\"})",
     "legendFormat": "Average Mem (REST)"
    },
    {
     "expr": "avg(mem_rpc_server{job=\"node\"})",
     "legendFormat": "Average Mem (RPC)"
    }
   ]
  },
  {
   "title": "Average Mem (REST vs RPC)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "avg(mem_rest_server{job=\"node\"})",
     "legendFormat": "Average Mem (REST)"
    },
    {
     "expr": "avg(mem_rpc_server{job=\"node\"})",
     "legendFormat": "Average Mem (RPC)"
    }
   ]
  },
  {
   "title": "Used mem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}) by (hostname) - sum(node_memory_MemFree_bytes{job=\"node-exporter\"}) by (hostname))",
     "legendFormat": "used: [{{hostname}}]"
    }
   ]
  },
  {
   "title": "Available mem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 55 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"node-exporter\"}",
     "legendFormat": "available: [{{hostname}}]"
    }
   ]
  },
  {
   "title": "Mem Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_total{job=\"node\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Application Mem Usage (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "%" }
   ],
   "targets": [
    {
     "expr": "sum(mem_total{job=\"node\"}) by (hostname) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}) by (hostname) * 100 ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Mem Deploy Gossiper",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "mem_deploy_gossiper{job=\"node\"} / (1024 * 1024)",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Mem Block Proposer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "decbytes", "label": "mem" }
   ],
   "targets": [
    {
     "expr": "mem_block_proposer{job=\"node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Mem Consensus",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 74 },
   "yaxes": [
    { "format": "decbytes", "label": "mem" }
   ],
   "targets": [
    {
     "expr": "mem_consensus{job=\"node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Mem Block Executor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "decbytes", "label": "mem" }
   ],
   "targets": [
    {
     "expr": "mem_block_executor{job=\"node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Mem Block Validator",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 80 },
   "yaxes": [
    { "format": "decbytes", "label": "mem" }
   ],
   "targets": [
    {
     "expr": "mem_proto_block_validator{job=\"node\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Mem Linear Chain",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 80 },
   "yaxes": [
    { "format": "decbytes", "label": "mem" }
   ],
   "targets": [
    {
     "expr": "mem_linear_chain{job=\"node\"} / 1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gossiper received vs onwards min/median/max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "percent", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "max((address_gossiper_items_gossiped_onwards{job=\"node\"} / address_gossiper_items_received{job=\"node\"}) * 100)",
     "legendFormat": "max"
    }
   ]
  }
 ]
}